development:
  adapter: postgresql
  database: development
  username: db
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: development
  username: db
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: development
  username: db
  password: postgres
  host: localhost