development:
  adapter: postgresql
  database:
  username:
  password:
  host:

test:
  adapter: postgresql
  database:
  username:
  password:
  host:

production:
  adapter: postgresql
  database:
  username:
  password:
  host: